# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20170418_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4000)),
                ('thumb', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True)),
                ('category', models.ManyToManyField(blank=True, default=None, to='blog.PostCategory')),
            ],
        ),
    ]
