# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_link',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
