# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_proj_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_link',
            field=models.CharField(blank=True, default=None, max_length=800),
        ),
    ]
