# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170701_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(default='/static/defaults/thumb_default.jpg', upload_to=''),
        ),
    ]
