# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170805_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='projects.ProjectCategory'),
        ),
    ]
