# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 15:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', ckeditor.fields.RichTextField(max_length=4000)),
            ],
        ),
    ]
