# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codepost_title', models.CharField(max_length=100)),
                ('codepost_content', models.TextField(max_length=1000)),
                ('codepost_date', models.DateTimeField(default=datetime.datetime(2017, 4, 2, 19, 10, 15, 151902, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='codepost',
            name='codepost_category',
            field=models.ManyToManyField(to='blog.PostCategory'),
        ),
    ]
