# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='blog.PostCategory'),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='content',
            field=ckeditor.fields.RichTextField(default='bar', max_length=4000),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='title',
            field=models.CharField(default='foo', max_length=100),
        ),
    ]
