# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='codepost_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='codepost_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 19, 23, 16, 908791, tzinfo=utc)),
        ),
    ]
