# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170418_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepost',
            name='thumb',
            field=models.ImageField(default='/static/defaults/thumb_default.jpg', upload_to=''),
        ),
    ]
