# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_codepost_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='thumb',
            field=models.ImageField(default='/static/media/thumb_default.jpg', upload_to=''),
        ),
    ]
