# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170817_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='thumb',
            field=models.FileField(default='/static/media/thumb_default.jpg', upload_to=''),
        ),
    ]
