# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170827_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='thumb',
            field=models.ImageField(default='/static/media/thumb_default.jpg', upload_to=''),
        ),
    ]
